### ISSUE TITLE
无法禁言管理员

### ISSUE THREAD

**Issue by Agnes4m** [zhulinyv/nonebot_plugin_easy_group_manager#1]
自己是群主，获取参数后，可以设置管理员，但是对管理员无法禁言，但是群主应该是可以禁言管理员的。
机器人返回 '权限不足捏'

**Comment by zhulinyv** [comment]
禁言管理员需要 BOT 为群主，skey 和 pskey 的作用只是在 BOT 非群主时设置管理员。

**Comment by Agnes4m** [comment]
那有没有办法实现呢，还有设置头衔这样的？

**Comment by zhulinyv** [comment]
目前没有可以直接禁言的 API。设置头衔也需要 BOT 为群主。由于 BOT 在有些群不可能成为群主，因此这个插件在写的时候直接忽略了需要群主权限的功能。如果需要的话可以去看 [多功能群管](https://github.com/HuYihe2008/nonebot_plugin_groupmanager) 。
